In [45]:
import numpy as np  #numpy의 별칭 np
print(np.__version__)

1.26.4


- 데이터 분석 : 수치형 변수의 요약, 통계, 시각화
- 이미지처리 : 이미지데이터 
- 게임/시뮬레이션 : 시뮬레이션 구현
- 머신러닝/딥러닝 : 금융,의료,실험,센서 데이터


In [46]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))  # [1 2 3 4 5]
arr.shape

[1 2 3 4 5] <class 'numpy.ndarray'>


(5,)

# 넘파이 배열의 속성 ndarray

In [47]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("합계:", arr.sum())          # 21
print("평균:", arr.mean())         # 3.5
print("표준편차:", arr.std())      # 1.707825127659933
print("행 방향 합계:", arr.sum(axis=1))  # [6 15]
print("열 방향 평균:", arr.mean(axis=0))  # [2.5 3.5 4.5]
arr.shape

합계: 21
평균: 3.5
표준편차: 1.707825127659933
행 방향 합계: [ 6 15]
열 방향 평균: [2.5 3.5 4.5]


(2, 3)

In [48]:
np.array(7).shape, np.array(7).ndim #0차원

((), 0)

In [49]:
np.array([7]).shape , np.array([7]).ndim #1차원,열1개

((1,), 1)

In [50]:
np.array([7,2]).shape, np.array([7,2]).ndim #1차원,열2개

((2,), 1)

In [51]:
arr1 = np.array([1, 2, 3, 4, 5]) #arr1.shape : (5,0)
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) #arr12.shape : (2,5)

arr1.shape, arr12.shape

((5,), (2, 5))

In [52]:
# (3,5) 행렬 arr13 만들기

In [53]:
arr13 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    []
]) #arr12.shape : (2,5)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
arr13 = np.arange(1, 16).reshape(3,5)
arr13.shape

(3, 5)

In [ ]:
arr13.dtype

dtype('int64')

# array 의 생성법

In [ ]:
# 0으로 채워진 배열 생성
arr2 = np.zeros(5)

# 1로 채워진 배열 생성
arr3 = np.ones((3, 3))

# 1부터 10까지 2씩 증가하는 배열
range_arr = np.arange(1, 10, 2)  
print(range_arr)

 # 0부터 100까지 5개의 숫자를 균등 간격으로 생성
linspace_arr = np.linspace(0, 100, 5) 
print(linspace_arr)

# 2행 3열의 랜덤 값 배열 (0~1 사이)
random_arr = np.random.rand(2, 3) 
print(random_arr)

[1 3 5 7 9]
[  0.  25.  50.  75. 100.]
[[0.98538556 0.5413886  0.37655458]
 [0.52385035 0.03210068 0.08654252]]


# 넘파이의 데이터타입

In [ ]:
# 다양한 데이터 타입의 배열 생성
#dtype 속성; np.int32 상수, ‘int32’ 문자열 형식으로 지정
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)
bool_array = np.array([True, False, True], dtype=np.bool_)

print("정수 배열의 dtype:", int_array.dtype)
print("실수 배열의 dtype:", float_array.dtype)
print("불리언 배열의 dtype:", bool_array.dtype)

정수 배열의 dtype: int32
실수 배열의 dtype: float64
불리언 배열의 dtype: bool


# array 의 데이터 타입 변환

In [ ]:
# 데이터 타입 변환 예제
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(np.int32)  # 실수를 정수로 변환
print("변환 전:", float_arr, float_arr.dtype)
print("변환 후:", int_arr, int_arr.dtype)

변환 전: [1.1 2.2 3.3] float64
변환 후: [1 2 3] int32


In [ ]:
arr_str = np.array(['1', '2', 'three'])  # 'three'는 숫자로 변환 불가
arr_int = arr_str.astype(int)  # 오류 발생
#ValueError: invalid literal for int() with base 10: np.str_('three')

ValueError: invalid literal for int() with base 10: np.str_('three')

In [ ]:
arr_str.dtype

dtype('<U5')

In [ ]:
# 1차원 배열 생성
a = np.arange(12)
print(a)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 2차원 배열로 변환 (3x4)
b = a.reshape(3, 4)
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# 3차원 배열로 변환 (2x2x3)
c = a.reshape(2, 2, 3)
print(c)
# [[[ 0  1  2]
#   [ 3  4  5]]
#  [[ 6  7  8]
#   [ 9 10 11]]]

In [ ]:
data = [
    [120, 135, 150, 145],  # 제품A
    [100, 110, 140, 130],  # 제품B
    [90, 100, 95, 105] ] #제품C

type(data)

list

In [ ]:
# 생산량 합계 확인
total_production = [sum(product) for product in data]
total_production

[550, 480, 390]

In [ ]:
prod_data = np.array(data)
prod_data.shape

(3, 4)

In [ ]:
prod_data

array([[120, 135, 150, 145],
       [100, 110, 140, 130],
       [ 90, 100,  95, 105]])

In [ ]:
np.sum(prod_data, axis=1)

array([550, 480, 390])

In [ ]:
np.sum(prod_data, axis=0)

array([310, 345, 385, 380])

In [ ]:
prod_data*2

array([[240, 270, 300, 290],
       [200, 220, 280, 260],
       [180, 200, 190, 210]])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)  # [3, 4, 5, 6, 7]
print(arr * 3)  # [3, 6, 9, 12, 15]
print(2 ** arr)  # [2, 4, 8, 16, 32]

[3 4 5 6 7]
[ 3  6  9 12 15]
[ 2  4  8 16 32]


In [ ]:
# 기본 산술 연산 예제 : 요소별 연산 elements wise
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# 덧셈
print("덧셈:", arr1 + arr2)  # [6 8 10 12]

# 뺄셈
print("뺄셈:", arr2 - arr1)  # [4 4 4 4]

# 곱셈
print("곱셈:", arr1 * arr2)  # [5 12 21 32]

# 나눗셈
print("나눗셈:", arr2 / arr1)  # [5. 3. 2.33... 2.]

# 제곱
print("제곱:", np.square(arr1))  # [1 4 9 16]

# 제곱근
print("제곱근:", np.sqrt(arr1))  # [1. 1.41421356 1.73205081 2.]

# 지수
print("지수:", np.exp(arr1))  # [2.71828183 7.3890561 20.08553692 54.59815003]

# 로그
print("로그:", np.log(arr1))  # [0. 0.69314718 1.09861229 1.38629436]

덧셈: [ 6  8 10 12]
뺄셈: [4 4 4 4]
곱셈: [ 5 12 21 32]
나눗셈: [5.         3.         2.33333333 2.        ]
제곱: [ 1  4  9 16]
제곱근: [1.         1.41421356 1.73205081 2.        ]
지수: [ 2.71828183  7.3890561  20.08553692 54.59815003]
로그: [0.         0.69314718 1.09861229 1.38629436]


In [ ]:
prod_data

array([[120, 135, 150, 145],
       [100, 110, 140, 130],
       [ 90, 100,  95, 105]])

In [ ]:
# 생산량 * 단가(이익율) = 총매출(총이익)
profit_per_unit = np.array([20,30,25])

In [ ]:
# 제품별 총 생산량 
total_produc = prod_data.sum(axis=1)
total_produc

array([550, 480, 390])

In [ ]:
# 총생산량 * 단가
total_amt = total_produc * profit_per_unit
total_amt

array([11000, 14400,  9750])

# shape 이 다른 배열간 연산에서 ValueError

In [ ]:
# shape이 같은 배열 간의 연산
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("덧셈:\n", a + b)
print("뺄셈:\n", a - b)
print("곱셈:\n", a * b)
print("나눗셈:\n", a / b)

# shape이 다른 경우 오류 발생
c = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
d = np.array([[1, 2], [3, 4]])        # shape: (2, 2)

# 이 연산은 오류를 발생시킴
print(c + d)  # ValueError: operands could not be broadcast together

덧셈:
 [[ 6  8]
 [10 12]]
뺄셈:
 [[-4 -4]
 [-4 -4]]
곱셈:
 [[ 5 12]
 [21 32]]
나눗셈:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

# 유니버설 함수 예제

In [ ]:
# 유니버설 함수 예제
arr = np.array([1, 2, 3, 4])

# 수학 함수
print("제곱:", np.power(arr, 2))  # [1 4 9 16]
print("제곱근:", np.sqrt(arr))    # [1. 1.41421356 1.73205081 2.]

# 삼각 함수
angles = np.array([0, 30, 45, 60]) * np.pi / 180
print("사인:", np.sin(angles))

# 로그 함수
print("자연로그:", np.log(arr))
print("로그10:", np.log10(arr))

제곱: [ 1  4  9 16]
제곱근: [1.         1.41421356 1.73205081 2.        ]
사인: [0.         0.5        0.70710678 0.8660254 ]
자연로그: [0.         0.69314718 1.09861229 1.38629436]
로그10: [0.         0.30103    0.47712125 0.60205999]


# 브로드캐스팅 예제

In [ ]:
# 브로드캐스팅 예제
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
scalar = 2

# 배열과 스칼라의 연산
print("배열 * 스칼라:")
print(arr * scalar)
# [[ 2  4  6]
#  [ 8 10 12]]

# 1차원 배열과 2차원 배열의 연산
row = np.array([1, 0, 1])
print("\n2차원 배열 + 1차원 배열:")
print(arr + row)
# [[2 2 4]
#  [5 5 7]]

배열 * 스칼라:
[[ 2  4  6]
 [ 8 10 12]]

2차원 배열 + 1차원 배열:
[[2 2 4]
 [5 5 7]]


In [ ]:
import numpy as np

a = np.arange(3)          # [0 1 2]
b = 5                     # 스칼라

result = a + b
print("a        :", a)        # [0 1 2]
print("b        :", b)        # 5
print("a + b    :", result)   # [5 6 7]
print("shape a  :", a.shape)  # (3,)
print("shape 결과:", result.shape)  # (3,)

a        : [0 1 2]
b        : 5
a + b    : [5 6 7]
shape a  : (3,)
shape 결과: (3,)


In [ ]:
a = np.ones((3, 3))       # 3x3 전부 1
b = np.arange(3)          # [0 1 2]

result = a + b
print("a :\n", a)
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]

print("b        :", b)         # [0 1 2]
print("shape a  :", a.shape)   # (3, 3)
print("shape b  :", b.shape)   # (3,)  → (1,3)으로 자동 확장

print("결과:\n", result)
# [[1. 2. 3.]
#  [1. 2. 3.]
#  [1. 2. 3.]]
print("shape 결과:", result.shape)  # (3, 3)

a :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
b        : [0 1 2]
shape a  : (3, 3)
shape b  : (3,)
결과:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
shape 결과: (3, 3)


In [ ]:
a = np.ones((3, 1))       # 3행 1열
b = np.arange(3)          # [0 1 2]

result = a + b
print("a :\n", a)
# [[1.]
#  [1.]
#  [1.]]

print("b        :", b)         # [0 1 2]
print("shape a  :", a.shape)   # (3, 1)
print("shape b  :", b.shape)   # (3,) → (1, 3)으로 자동 확장

print("결과:\n", result)
# [[1. 2. 3.]
#  [2. 3. 4.]   ← ones의 값이 0,1,2로 달라서 결과가 다름
#  [3. 4. 5.]]
print("shape 결과:", result.shape)  # (3, 3)


a :
 [[1.]
 [1.]
 [1.]]
b        : [0 1 2]
shape a  : (3, 1)
shape b  : (3,)
결과:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
shape 결과: (3, 3)


# 1차원、 ２차원 배열 인덱싱

In [ ]:
# 1차원 배열 인덱싱
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])    # 첫 번째 요소: 1
print(arr[-1])   # 마지막 요소: 5

1
5


In [60]:
# 2차원 배열 인덱싱
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d[0, 1])    # 첫 번째 행, 두 번째 열: 2
print(arr_2d[1, -1])   # 두 번째 행, 마지막 열: 6
print(arr_2d[1, 1])

2
6
5


In [ ]:
# 슬라이싱 [시작 인덱스: 끝 인덱스: 간격 형식]

In [62]:
# 1차원 배열 슬라이싱
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:5])    # [2 3 4]
print(arr[::2])    # [0 2 4]

# 2차원 배열 슬라이싱
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[:2, 1:3])    # 처음 두 행, 두 번째와 세 번째 열
# [[2 3]
#  [6 7]]

[2 3 4]
[0 2 4]
[[2 3]
 [6 7]]


# 1차원 배열 인덱싱 예제

In [ ]:
# 1차원 배열 인덱싱 예제
arr = np.array([10, 20, 30, 40, 50])

# 단일 요소 접근
print("첫 번째 요소:", arr[0])      # 10
print("마지막 요소:", arr[-1])      # 50

# 슬라이싱
print("처음부터 3개:", arr[:3])     # [10 20 30]
print("2번째부터 끝까지:", arr[2:]) # [30 40 50]
print("처음부터 끝까지 2단계씩:", arr[::2]) # [10 30 50]

첫 번째 요소: 10
마지막 요소: 50
처음부터 3개: [10 20 30]
2번째부터 끝까지: [30 40 50]
처음부터 끝까지 2단계씩: [10 30 50]


In [66]:
# 1면 (6x6) 을 4번 쌓기
face = np.arange(36).reshape(6, 6)
arr_3d_new = np.array([face] * 4)

print("shape:", arr_3d_new.shape)  # (4, 6, 6)
print(arr_3d_new)

shape: (4, 6, 6)
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [67]:
# 슬라이싱
result = arr_3d_new[0, :3, :3]
print(result)
# [[ 0  1  2]
#  [ 6  7  8]
#  [12 13 14]]

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


# 불린 인덱싱 예제

In [ ]:
# 불린 인덱싱 예제
arr = np.array([1, 2, 3, 4, 5])
bool_array = np.array([True, False, True, False, True])
print("불린 인덱싱:", arr[bool_array])  # [1 3 5]

# 팬시인덱싱